#!/usr/bin/env bash
#
# Creates all the VMs for the POC. All VMs get public IPs because that's a simple way to
# automatically enable outbound traffic for yum functionality. Note - the instance settings
# make sense for my account - of course you will have to tweak them. Note that
# CentOS-7-2111-2022*x86_64 is an Amazon image that requires you to subscribe it and
# accept the EULA in the management console. Per:
#
# https://aws.amazon.com/marketplace/server/procurement?productId=d9a3032a-921c-4c6d-b150-bde168105e42
#
# Consider running 'provision-ec2-instancez' first by hand with the --dry-run arg to validate
# AWS values.
#

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

instance_type=t2.xlarge
storage=200

for vmname in d2iq-bootstrap d2iq-cp1 d2iq-cp2 d2iq-cp3 d2iq-w1 d2iq-w2 d2iq-w3; do
  $script_dir/provision-ec2-instancez\
    --vol-size $storage \
    --public-ip y \
    --nowait \
    $(pwd)/d2iq \
    vpc-0aab67dd3a3216872 \
    us-east-1a \
    default \
    'CentOS-7-2111-2022*x86_64' \
    $instance_type \
    $vmname || break
done
